//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crosswind.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppUris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppUris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crosswind.Resources.AppUris", typeof(AppUris).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AboutPage.xaml.
        /// </summary>
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.xaml.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunwayPage.xaml.
        /// </summary>
        internal static string RunwayPage {
            get {
                return ResourceManager.GetString("RunwayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/.
        /// </summary>
        internal static string ViewsDir {
            get {
                return ResourceManager.GetString("ViewsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindHeadingPage.xaml.
        /// </summary>
        internal static string WindHeadingPage {
            get {
                return ResourceManager.GetString("WindHeadingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindSpeedPage.xaml.
        /// </summary>
        internal static string WindSpeedPage {
            get {
                return ResourceManager.GetString("WindSpeedPage", resourceCulture);
            }
        }
    }
}
